# Jekyll workshop template
# based on minima theme https://github.com/jekyll/minima

title: Get Git!
description: > 
  Learn about git version control and GitHub for fun and profit. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uidaholib.github.io/get-git" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# note: fig include, {% include image.html file="my-cat.jpg" alt="cat" cap="My cat" %}