# Jekyll workshop-template https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

title: Get Git!
description: > 
  Learn about git version control and GitHub for fun and profit. 
keywords: "git, github, workshop, version control"

url: "https://uidaholib.github.io/get-git" # the base hostname & protocol for your site

google_analytics: UA-74844011-1

# author settings for cc-by
author: evan will
github_username: evanwill
pub_year: 2017
repo: "https://github.com/uidaholib/get-git"

# Build settings
markdown: kramdown

# note: fig include, {% include image.html file="my-cat.jpg" alt="cat" cap="My cat" %}